# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://ocelotconsulting.com
title: Ocelot Consulting
email: info@ocelotconsulting.com
author: Ocelot Developers
description: >
  Ocelot Consultants are certified AWS Solution Architects and have experience
  migrating enterprise applications and data for Fortune 500 companies.
copyright: 'Copyright &copy; 2018 Ocelot Consulting LLC. All Rights Reserved.'
about: >
  Ocelot Consulting specializes in cloud technologies, custom application development
  and enterprise security. Ocelot Consultants are certified AWS Solution Architects
  and have experience migrating enterprise applications and data for Fortune 500 companies.

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
timezone: America/Chicago
encoding: utf-8
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - rouge
paginate: 5
paginate_path: "/posts/page:num/"
sass:
  style: compact # possible values: nested expanded compact compressed

# Markdown conversion
markdown: kramdown
markdown_ext: "md"
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: html
    css_class: 'syntax'

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    url: https://github.com/ocelotconsulting/
  - title: linkedin
    url: https://www.linkedin.com/company/ocelot-consulting-llc
  - title: rss
    url: /feed.xml
  - title: slack
    url: https://join.slack.com/t/ocelot-consulting-pub/shared_invite/zt-fbfmqoz9-30Ur9KmHYALDm17akmGOng

contactForm:
  url: https://9qpcx5jjib.execute-api.us-east-1.amazonaws.com/prod/
  # url: https://bai15rjzze.execute-api.us-east-1.amazonaws.com/poc
  to: info@ocelotconsulting.com
  redirect: https://ocelotconsulting.com
recaptcha:
  # siteKey: 6LdnFgEVAAAAAKcCPOLnl3G3ERGDivtzYYkhOvVI # local development
  siteKey: 6LduFgEVAAAAAJLy0R672PEdTafugaVHktVYcMLD # production